/* 
 * Res.Grosvenor - Rank
 *
 * Rank Enterprise Services API is a collection of business services exposed over a RESTful inteface. This endpoint is specific to Grosvenor Casinos implementation.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AccrueLoyaltyPointsRequest
    /// </summary>
    [DataContract]
    public partial class AccrueLoyaltyPointsRequest :  IEquatable<AccrueLoyaltyPointsRequest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccrueLoyaltyPointsRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AccrueLoyaltyPointsRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AccrueLoyaltyPointsRequest" /> class.
        /// </summary>
        /// <param name="CardNo"> (required).</param>
        /// <param name="LocationId"> (required).</param>
        /// <param name="Points"> (required).</param>
        /// <param name="TransDateTime"> (required).</param>
        public AccrueLoyaltyPointsRequest(int? CardNo = null, string LocationId = null, int? Points = null, string TransDateTime = null)
        {
            // to ensure "CardNo" is required (not null)
            if (CardNo == null)
            {
                throw new InvalidDataException("CardNo is a required property for AccrueLoyaltyPointsRequest and cannot be null");
            }
            else
            {
                this.CardNo = CardNo;
            }
            // to ensure "LocationId" is required (not null)
            if (LocationId == null)
            {
                throw new InvalidDataException("LocationId is a required property for AccrueLoyaltyPointsRequest and cannot be null");
            }
            else
            {
                this.LocationId = LocationId;
            }
            // to ensure "Points" is required (not null)
            if (Points == null)
            {
                throw new InvalidDataException("Points is a required property for AccrueLoyaltyPointsRequest and cannot be null");
            }
            else
            {
                this.Points = Points;
            }
            // to ensure "TransDateTime" is required (not null)
            if (TransDateTime == null)
            {
                throw new InvalidDataException("TransDateTime is a required property for AccrueLoyaltyPointsRequest and cannot be null");
            }
            else
            {
                this.TransDateTime = TransDateTime;
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="CardNo", EmitDefaultValue=false)]
        public int? CardNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="LocationId", EmitDefaultValue=false)]
        public string LocationId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="Points", EmitDefaultValue=false)]
        public int? Points { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="TransDateTime", EmitDefaultValue=false)]
        public string TransDateTime { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AccrueLoyaltyPointsRequest {\n");
            sb.Append("  CardNo: ").Append(CardNo).Append("\n");
            sb.Append("  LocationId: ").Append(LocationId).Append("\n");
            sb.Append("  Points: ").Append(Points).Append("\n");
            sb.Append("  TransDateTime: ").Append(TransDateTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AccrueLoyaltyPointsRequest);
        }

        /// <summary>
        /// Returns true if AccrueLoyaltyPointsRequest instances are equal
        /// </summary>
        /// <param name="other">Instance of AccrueLoyaltyPointsRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccrueLoyaltyPointsRequest other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.CardNo == other.CardNo ||
                    this.CardNo != null &&
                    this.CardNo.Equals(other.CardNo)
                ) && 
                (
                    this.LocationId == other.LocationId ||
                    this.LocationId != null &&
                    this.LocationId.Equals(other.LocationId)
                ) && 
                (
                    this.Points == other.Points ||
                    this.Points != null &&
                    this.Points.Equals(other.Points)
                ) && 
                (
                    this.TransDateTime == other.TransDateTime ||
                    this.TransDateTime != null &&
                    this.TransDateTime.Equals(other.TransDateTime)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.CardNo != null)
                    hash = hash * 59 + this.CardNo.GetHashCode();
                if (this.LocationId != null)
                    hash = hash * 59 + this.LocationId.GetHashCode();
                if (this.Points != null)
                    hash = hash * 59 + this.Points.GetHashCode();
                if (this.TransDateTime != null)
                    hash = hash * 59 + this.TransDateTime.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
