/* 
 * Res.Grosvenor - Rank
 *
 * Rank Enterprise Services API is a collection of business services exposed over a RESTful inteface. This endpoint is specific to Grosvenor Casinos implementation.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request
    /// </summary>
    [DataContract]
    public partial class MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request :  IEquatable<MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request" /> class.
        /// </summary>
        /// <param name="PlayerId"> (required).</param>
        /// <param name="CardNo"> (required).</param>
        /// <param name="DateofBirth"> (required).</param>
        public MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request(int? PlayerId = null, int? CardNo = null, string DateofBirth = null)
        {
            // to ensure "PlayerId" is required (not null)
            if (PlayerId == null)
            {
                throw new InvalidDataException("PlayerId is a required property for MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request and cannot be null");
            }
            else
            {
                this.PlayerId = PlayerId;
            }
            // to ensure "CardNo" is required (not null)
            if (CardNo == null)
            {
                throw new InvalidDataException("CardNo is a required property for MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request and cannot be null");
            }
            else
            {
                this.CardNo = CardNo;
            }
            // to ensure "DateofBirth" is required (not null)
            if (DateofBirth == null)
            {
                throw new InvalidDataException("DateofBirth is a required property for MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request and cannot be null");
            }
            else
            {
                this.DateofBirth = DateofBirth;
            }
        }
        
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="PlayerId", EmitDefaultValue=false)]
        public int? PlayerId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="CardNo", EmitDefaultValue=false)]
        public int? CardNo { get; set; }
        /// <summary>
        /// 
        /// </summary>
        /// <value></value>
        [DataMember(Name="DateofBirth", EmitDefaultValue=false)]
        public string DateofBirth { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request {\n");
            sb.Append("  PlayerId: ").Append(PlayerId).Append("\n");
            sb.Append("  CardNo: ").Append(CardNo).Append("\n");
            sb.Append("  DateofBirth: ").Append(DateofBirth).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request);
        }

        /// <summary>
        /// Returns true if MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request instances are equal
        /// </summary>
        /// <param name="other">Instance of MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MergeExistingDigitalAndRetailLoyaltyAccountsFlavour2Request other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.PlayerId == other.PlayerId ||
                    this.PlayerId != null &&
                    this.PlayerId.Equals(other.PlayerId)
                ) && 
                (
                    this.CardNo == other.CardNo ||
                    this.CardNo != null &&
                    this.CardNo.Equals(other.CardNo)
                ) && 
                (
                    this.DateofBirth == other.DateofBirth ||
                    this.DateofBirth != null &&
                    this.DateofBirth.Equals(other.DateofBirth)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.PlayerId != null)
                    hash = hash * 59 + this.PlayerId.GetHashCode();
                if (this.CardNo != null)
                    hash = hash * 59 + this.CardNo.GetHashCode();
                if (this.DateofBirth != null)
                    hash = hash * 59 + this.DateofBirth.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
