/* 
 * Res.Grosvenor - Rank
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CasinoEventsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CasinoEventsResponseTests
    {
        // TODO uncomment below to declare an instance variable for CasinoEventsResponse
        //private CasinoEventsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CasinoEventsResponse
            //instance = new CasinoEventsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CasinoEventsResponse
        /// </summary>
        [Test]
        public void CasinoEventsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CasinoEventsResponse
            //Assert.IsInstanceOfType<CasinoEventsResponse> (instance, "variable 'instance' is a CasinoEventsResponse");
        }

        /// <summary>
        /// Test the property 'CasinoNumber'
        /// </summary>
        [Test]
        public void CasinoNumberTest()
        {
            // TODO unit test for the property 'CasinoNumber'
        }
        /// <summary>
        /// Test the property 'CategoryId'
        /// </summary>
        [Test]
        public void CategoryIdTest()
        {
            // TODO unit test for the property 'CategoryId'
        }
        /// <summary>
        /// Test the property 'Category'
        /// </summary>
        [Test]
        public void CategoryTest()
        {
            // TODO unit test for the property 'Category'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'ValidFrom'
        /// </summary>
        [Test]
        public void ValidFromTest()
        {
            // TODO unit test for the property 'ValidFrom'
        }
        /// <summary>
        /// Test the property 'ValidTo'
        /// </summary>
        [Test]
        public void ValidToTest()
        {
            // TODO unit test for the property 'ValidTo'
        }
        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Test]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'EventSchedule'
        /// </summary>
        [Test]
        public void EventScheduleTest()
        {
            // TODO unit test for the property 'EventSchedule'
        }
        /// <summary>
        /// Test the property 'EventStartTime'
        /// </summary>
        [Test]
        public void EventStartTimeTest()
        {
            // TODO unit test for the property 'EventStartTime'
        }
        /// <summary>
        /// Test the property 'EventFacebookUrl'
        /// </summary>
        [Test]
        public void EventFacebookUrlTest()
        {
            // TODO unit test for the property 'EventFacebookUrl'
        }

    }

}
