/* 
 * Res.Grosvenor - Rank
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CasinoPokerSchedulesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CasinoPokerSchedulesResponseTests
    {
        // TODO uncomment below to declare an instance variable for CasinoPokerSchedulesResponse
        //private CasinoPokerSchedulesResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CasinoPokerSchedulesResponse
            //instance = new CasinoPokerSchedulesResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CasinoPokerSchedulesResponse
        /// </summary>
        [Test]
        public void CasinoPokerSchedulesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CasinoPokerSchedulesResponse
            //Assert.IsInstanceOfType<CasinoPokerSchedulesResponse> (instance, "variable 'instance' is a CasinoPokerSchedulesResponse");
        }

        /// <summary>
        /// Test the property 'CasinoNumber'
        /// </summary>
        [Test]
        public void CasinoNumberTest()
        {
            // TODO unit test for the property 'CasinoNumber'
        }
        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Test]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }
        /// <summary>
        /// Test the property 'StartDate'
        /// </summary>
        [Test]
        public void StartDateTest()
        {
            // TODO unit test for the property 'StartDate'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'Game'
        /// </summary>
        [Test]
        public void GameTest()
        {
            // TODO unit test for the property 'Game'
        }
        /// <summary>
        /// Test the property 'GameType'
        /// </summary>
        [Test]
        public void GameTypeTest()
        {
            // TODO unit test for the property 'GameType'
        }
        /// <summary>
        /// Test the property 'Stake'
        /// </summary>
        [Test]
        public void StakeTest()
        {
            // TODO unit test for the property 'Stake'
        }
        /// <summary>
        /// Test the property 'StartingStake'
        /// </summary>
        [Test]
        public void StartingStakeTest()
        {
            // TODO unit test for the property 'StartingStake'
        }
        /// <summary>
        /// Test the property 'RegFee'
        /// </summary>
        [Test]
        public void RegFeeTest()
        {
            // TODO unit test for the property 'RegFee'
        }
        /// <summary>
        /// Test the property 'StartTime'
        /// </summary>
        [Test]
        public void StartTimeTest()
        {
            // TODO unit test for the property 'StartTime'
        }

    }

}
