/* 
 * Res.Grosvenor - Rank
 *
 * Rank Enterprise Services API is a collection of business services exposed over a RESTful inteface. This endpoint is specific to Grosvenor Casinos implementation.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CasinoPokerCashGamesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CasinoPokerCashGamesResponseTests
    {
        // TODO uncomment below to declare an instance variable for CasinoPokerCashGamesResponse
        //private CasinoPokerCashGamesResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CasinoPokerCashGamesResponse
            //instance = new CasinoPokerCashGamesResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CasinoPokerCashGamesResponse
        /// </summary>
        [Test]
        public void CasinoPokerCashGamesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CasinoPokerCashGamesResponse
            //Assert.IsInstanceOfType<CasinoPokerCashGamesResponse> (instance, "variable 'instance' is a CasinoPokerCashGamesResponse");
        }

        /// <summary>
        /// Test the property 'CasinoNumber'
        /// </summary>
        [Test]
        public void CasinoNumberTest()
        {
            // TODO unit test for the property 'CasinoNumber'
        }
        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Test]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }
        /// <summary>
        /// Test the property 'Start'
        /// </summary>
        [Test]
        public void StartTest()
        {
            // TODO unit test for the property 'Start'
        }
        /// <summary>
        /// Test the property 'End'
        /// </summary>
        [Test]
        public void EndTest()
        {
            // TODO unit test for the property 'End'
        }
        /// <summary>
        /// Test the property 'NumberOfGames'
        /// </summary>
        [Test]
        public void NumberOfGamesTest()
        {
            // TODO unit test for the property 'NumberOfGames'
        }
        /// <summary>
        /// Test the property 'StakeFrom'
        /// </summary>
        [Test]
        public void StakeFromTest()
        {
            // TODO unit test for the property 'StakeFrom'
        }
        /// <summary>
        /// Test the property 'StakeTo'
        /// </summary>
        [Test]
        public void StakeToTest()
        {
            // TODO unit test for the property 'StakeTo'
        }
        /// <summary>
        /// Test the property 'BlindsFrom'
        /// </summary>
        [Test]
        public void BlindsFromTest()
        {
            // TODO unit test for the property 'BlindsFrom'
        }
        /// <summary>
        /// Test the property 'BlindsTo'
        /// </summary>
        [Test]
        public void BlindsToTest()
        {
            // TODO unit test for the property 'BlindsTo'
        }
        /// <summary>
        /// Test the property 'SessionOrRake'
        /// </summary>
        [Test]
        public void SessionOrRakeTest()
        {
            // TODO unit test for the property 'SessionOrRake'
        }

    }

}
