/* 
 * Res.Grosvenor - Rank
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CasinoDetailsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CasinoDetailsResponseTests
    {
        // TODO uncomment below to declare an instance variable for CasinoDetailsResponse
        //private CasinoDetailsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CasinoDetailsResponse
            //instance = new CasinoDetailsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CasinoDetailsResponse
        /// </summary>
        [Test]
        public void CasinoDetailsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CasinoDetailsResponse
            //Assert.IsInstanceOfType<CasinoDetailsResponse> (instance, "variable 'instance' is a CasinoDetailsResponse");
        }

        /// <summary>
        /// Test the property 'Number'
        /// </summary>
        [Test]
        public void NumberTest()
        {
            // TODO unit test for the property 'Number'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Test]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }
        /// <summary>
        /// Test the property 'Town'
        /// </summary>
        [Test]
        public void TownTest()
        {
            // TODO unit test for the property 'Town'
        }
        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Test]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }
        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Test]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'RegionName'
        /// </summary>
        [Test]
        public void RegionNameTest()
        {
            // TODO unit test for the property 'RegionName'
        }
        /// <summary>
        /// Test the property 'Position'
        /// </summary>
        [Test]
        public void PositionTest()
        {
            // TODO unit test for the property 'Position'
        }
        /// <summary>
        /// Test the property 'CasinoManager'
        /// </summary>
        [Test]
        public void CasinoManagerTest()
        {
            // TODO unit test for the property 'CasinoManager'
        }
        /// <summary>
        /// Test the property 'SocialNetworkLinks'
        /// </summary>
        [Test]
        public void SocialNetworkLinksTest()
        {
            // TODO unit test for the property 'SocialNetworkLinks'
        }
        /// <summary>
        /// Test the property 'AboutCasino'
        /// </summary>
        [Test]
        public void AboutCasinoTest()
        {
            // TODO unit test for the property 'AboutCasino'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'Facilities'
        /// </summary>
        [Test]
        public void FacilitiesTest()
        {
            // TODO unit test for the property 'Facilities'
        }
        /// <summary>
        /// Test the property 'OpeningTimes'
        /// </summary>
        [Test]
        public void OpeningTimesTest()
        {
            // TODO unit test for the property 'OpeningTimes'
        }
        /// <summary>
        /// Test the property 'Games'
        /// </summary>
        [Test]
        public void GamesTest()
        {
            // TODO unit test for the property 'Games'
        }
        /// <summary>
        /// Test the property 'PanoramaUrl'
        /// </summary>
        [Test]
        public void PanoramaUrlTest()
        {
            // TODO unit test for the property 'PanoramaUrl'
        }
        /// <summary>
        /// Test the property 'BookATableConnectionDetails'
        /// </summary>
        [Test]
        public void BookATableConnectionDetailsTest()
        {
            // TODO unit test for the property 'BookATableConnectionDetails'
        }

    }

}
