/* 
 * Res.Grosvenor - Rank
 *
 * Rank Enterprise Services API is a collection of business services exposed over a RESTful inteface. This endpoint is specific to Grosvenor Casinos implementation.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing DiagnoseResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class DiagnoseResponseTests
    {
        // TODO uncomment below to declare an instance variable for DiagnoseResponse
        //private DiagnoseResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of DiagnoseResponse
            //instance = new DiagnoseResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of DiagnoseResponse
        /// </summary>
        [Test]
        public void DiagnoseResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DiagnoseResponse
            //Assert.IsInstanceOfType<DiagnoseResponse> (instance, "variable 'instance' is a DiagnoseResponse");
        }

        /// <summary>
        /// Test the property 'AzureTableStorage'
        /// </summary>
        [Test]
        public void AzureTableStorageTest()
        {
            // TODO unit test for the property 'AzureTableStorage'
        }
        /// <summary>
        /// Test the property 'MembershipDB'
        /// </summary>
        [Test]
        public void MembershipDBTest()
        {
            // TODO unit test for the property 'MembershipDB'
        }
        /// <summary>
        /// Test the property 'SpineRESTAPI'
        /// </summary>
        [Test]
        public void SpineRESTAPITest()
        {
            // TODO unit test for the property 'SpineRESTAPI'
        }
        /// <summary>
        /// Test the property 'BallyXMLAPI'
        /// </summary>
        [Test]
        public void BallyXMLAPITest()
        {
            // TODO unit test for the property 'BallyXMLAPI'
        }

    }

}
