/* 
 * Res.Grosvenor - Rank
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MergeDigitalAndRetailAccountsFlavour1Request
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MergeDigitalAndRetailAccountsFlavour1RequestTests
    {
        // TODO uncomment below to declare an instance variable for MergeDigitalAndRetailAccountsFlavour1Request
        //private MergeDigitalAndRetailAccountsFlavour1Request instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MergeDigitalAndRetailAccountsFlavour1Request
            //instance = new MergeDigitalAndRetailAccountsFlavour1Request();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MergeDigitalAndRetailAccountsFlavour1Request
        /// </summary>
        [Test]
        public void MergeDigitalAndRetailAccountsFlavour1RequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MergeDigitalAndRetailAccountsFlavour1Request
            //Assert.IsInstanceOfType<MergeDigitalAndRetailAccountsFlavour1Request> (instance, "variable 'instance' is a MergeDigitalAndRetailAccountsFlavour1Request");
        }

        /// <summary>
        /// Test the property 'PlayerId'
        /// </summary>
        [Test]
        public void PlayerIdTest()
        {
            // TODO unit test for the property 'PlayerId'
        }
        /// <summary>
        /// Test the property 'MembershipNo'
        /// </summary>
        [Test]
        public void MembershipNoTest()
        {
            // TODO unit test for the property 'MembershipNo'
        }

    }

}
