/* 
 * Res.Grosvenor - Rank
 *
 * TODO: Add a description
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RegisterThisOperationIsDisabledRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RegisterThisOperationIsDisabledRequestTests
    {
        // TODO uncomment below to declare an instance variable for RegisterThisOperationIsDisabledRequest
        //private RegisterThisOperationIsDisabledRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RegisterThisOperationIsDisabledRequest
            //instance = new RegisterThisOperationIsDisabledRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RegisterThisOperationIsDisabledRequest
        /// </summary>
        [Test]
        public void RegisterThisOperationIsDisabledRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RegisterThisOperationIsDisabledRequest
            //Assert.IsInstanceOfType<RegisterThisOperationIsDisabledRequest> (instance, "variable 'instance' is a RegisterThisOperationIsDisabledRequest");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'Nationality'
        /// </summary>
        [Test]
        public void NationalityTest()
        {
            // TODO unit test for the property 'Nationality'
        }
        /// <summary>
        /// Test the property 'TelephoneNumber'
        /// </summary>
        [Test]
        public void TelephoneNumberTest()
        {
            // TODO unit test for the property 'TelephoneNumber'
        }
        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Test]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }
        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [Test]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }
        /// <summary>
        /// Test the property 'EmailAddress'
        /// </summary>
        [Test]
        public void EmailAddressTest()
        {
            // TODO unit test for the property 'EmailAddress'
        }
        /// <summary>
        /// Test the property 'Club'
        /// </summary>
        [Test]
        public void ClubTest()
        {
            // TODO unit test for the property 'Club'
        }
        /// <summary>
        /// Test the property 'Contactable'
        /// </summary>
        [Test]
        public void ContactableTest()
        {
            // TODO unit test for the property 'Contactable'
        }
        /// <summary>
        /// Test the property 'ContactChannel'
        /// </summary>
        [Test]
        public void ContactChannelTest()
        {
            // TODO unit test for the property 'ContactChannel'
        }
        /// <summary>
        /// Test the property 'AgeVerified'
        /// </summary>
        [Test]
        public void AgeVerifiedTest()
        {
            // TODO unit test for the property 'AgeVerified'
        }

    }

}
