/* 
 * Res.Grosvenor - Rank
 *
 * Rank Enterprise Services API is a collection of business services exposed over a RESTful inteface. This endpoint is specific to Grosvenor Casinos implementation.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RetailMembershipV10Api
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class RetailMembershipV10ApiTests
    {
        private RetailMembershipV10Api instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new RetailMembershipV10Api();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RetailMembershipV10Api
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' RetailMembershipV10Api
            //Assert.IsInstanceOfType(typeof(RetailMembershipV10Api), instance, "instance is a RetailMembershipV10Api");
        }

        
        /// <summary>
        /// Test GetLookupValues
        /// </summary>
        [Test]
        public void GetLookupValuesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //bool? includeNationalities = null;
            //bool? includeCountries = null;
            //bool? incldueCasinos = null;
            //bool? includeTitles = null;
            //var response = instance.GetLookupValues(includeNationalities, includeCountries, incldueCasinos, includeTitles);
            //Assert.IsInstanceOf<GetLookupValuesResponse> (response, "response is GetLookupValuesResponse");
        }
        
        /// <summary>
        /// Test Lookup1
        /// </summary>
        [Test]
        public void Lookup1Test()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //double? membershipNo = null;
            //DateTime? dateOfBirth = null;
            //bool? checkAlreadyUsed = null;
            //var response = instance.Lookup1(membershipNo, dateOfBirth, checkAlreadyUsed);
            //Assert.IsInstanceOf<LookupResponse2> (response, "response is LookupResponse2");
        }
        
        /// <summary>
        /// Test RegisterThisOperationIsDisabled
        /// </summary>
        [Test]
        public void RegisterThisOperationIsDisabledTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //RegisterThisOperationIsDisabledRequest body = null;
            //instance.RegisterThisOperationIsDisabled(body);
            
        }
        
    }

}
