/*
 * Res.Grosvenor - Rank
 *
 * Rank Enterprise Services API is a collection of business services exposed over a RESTful inteface. This endpoint is specific to Grosvenor Casinos implementation.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.SwaggerGen.Annotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class LoyaltyV10ApiController : Controller
    { 

        /// <summary>
        /// Add digital Account
        /// </summary>
        /// <remarks>Adding the newly created digital account to the retail loyalty account and returns the points balance, Request body fields: | Name              | Type      | Required  | Description                                   | Example           | |:- --               |:- --       |:- --       |:- --                                           |:- --               | |PlayerId           |long       |Yes        |Customer identifier from the digital platform. |570515106383925248 | |MembershipNo       |string     |Yes        |Retail Casino membership number.               |123456789         |</remarks>
        /// <param name="body"></param>
        /// <response code="200"></response>
        [HttpPost]
        [Route("//loyalty/v1/accounts")]
        [SwaggerOperation("AddDigitalAccount")]
        [SwaggerResponse(200, type: typeof(AddDigitalAccountResponse))]
        public virtual IActionResult AddDigitalAccount([FromBody]AddDigitalAccountRequest body)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<AddDigitalAccountResponse>(exampleJson)
            : default(AddDigitalAccountResponse);
            return new ObjectResult(example);
        }


        /// <summary>
        /// Create customers playpoints account
        /// </summary>
        /// <remarks>| Name          | Type      | Required  | Description                                       | Example           | |:- --           |:- --       |:- --       |:- --                                               |:- --               | |PlayerId       |long       |yes        |Customer identifier from the digital platform.     |570515106383925248 | |Forename       |string     |yes        |first name of the customer                         |\&quot;Bob\&quot;              | |Surname        |string     |yes        |Last name of the customer                          |\&quot;Marley\&quot;           | |DateOfBirth    |Date       |yes        |Date of birth of the customer.                     |1982-04-28         |</remarks>
        /// <param name="body"></param>
        /// <response code="201"></response>
        [HttpPost]
        [Route("//loyalty/v1/customers/")]
        [SwaggerOperation("CreateCustomersPlaypointsAccount")]
        public virtual void CreateCustomersPlaypointsAccount([FromBody]CreateCustomersPlaypointsAccountRequest body)
        { 
            throw new NotImplementedException();
        }


        /// <summary>
        /// Merge Digital and Retail Accounts - flavour 2
        /// </summary>
        /// <remarks>This method is a varient of the above method which links the digital and retail loyalty accounts and merges the points earned. This can be used when retail membership number is not available to the client. Returns the combined points balance, Request body fields: | Name              | Type      | Required  | Description                                   | Example           | |:- --               |:- --       |:- --       |:- --                                           |:- --               | |PlayerId           |long       |Yes        |Customer identifier from the digital platform. |570515106383925248 | |CardNo             |int        |Yes        |Player loyalty Card number                     |1460040108         | |DateofBirth        |Date       |yes        |Date of birth of the customer.                 |1982-04-28         |</remarks>
        /// <param name="body"></param>
        /// <response code="200"></response>
        [HttpPut]
        [Route("//loyalty/v1/accounts")]
        [SwaggerOperation("MergeDigitalAndRetailAccountsFlavour2")]
        [SwaggerResponse(200, type: typeof(MergeDigitalAndRetailAccountsFlavour1Response))]
        public virtual IActionResult MergeDigitalAndRetailAccountsFlavour2([FromBody]MergeDigitalAndRetailAccountsFlavour2Request body)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<MergeDigitalAndRetailAccountsFlavour1Response>(exampleJson)
            : default(MergeDigitalAndRetailAccountsFlavour1Response);
            return new ObjectResult(example);
        }


        /// <summary>
        /// Redeem points
        /// </summary>
        /// <remarks>Redeem the playpoints balance, Request body fields: | Name              | Type      | Required  | Description                                       | Example               | |:- --               |:- --       |:- --       |:- --                                               |:- --                   | |PlayerId           |long       |yes        |Customer identifier from the digital platform.     |570515106383925248     | |Points             |int        |yes        |amount that needs adjusting                        |100                    | |RedeemDateTime     |DateTime   |yes        |Date and time of the redemption call.              |2015-04-28T10:10:25Z   | Response would be * OK (HTTP 200) - when redemption is successful * Bad Request (400) -       * the request parameters are not valid or      * the player hasn&#39;t got enough funds or      * the player has exceeded the daily redemption limit (Message: \&quot;Sorry, you can only redeem a maximum of 50000 PLAY Points in a day\&quot;) * Error (500) - when there is an error redeeming the points. Most likely cause would be ability to connect to other systems.</remarks>
        /// <param name="body"></param>
        /// <response code="200"></response>
        /// <response code="400">Unexpected error in API call. See HTTP response body for details.</response>
        /// <response code="0">Unexpected error in API call. See HTTP response body for details.</response>
        [HttpDelete]
        [Route("//loyalty/v1/points")]
        [SwaggerOperation("RedeemPoints")]
        public virtual void RedeemPoints([FromBody]RedeemPointsRequest body)
        { 
            throw new NotImplementedException();
        }


        /// <summary>
        /// Retrieve Points balance
        /// </summary>
        /// <remarks>Retrieves play points balance for the customer, any one of the below parameters is required. | Name          | Type  | Description                                       | Example           | |:- --           |:- --   |:- --                                               |:- --               | |playerId       |long   |Customer identifier from the digital platform.     |570515106383925248 | |cardNo         |number |Number on the back of the membership card.         |16227376           | |membershipNo   |string |Retail Casino membership number.                   |1850034070         | |testId       |long   |Customer identifier from the digital platform.     |570515106383925248 |</remarks>
        /// <param name="playerId">Customer identifier from the digital platform</param>
        /// <param name="cardNo">Number on the back of the membership card. If specified, then Grade will be returned.</param>
        /// <param name="membershipNo">Retail Casino membership number.</param>
        /// <param name="testMembershipNo">Retail test Casino membership number.</param>
        /// <response code="200"></response>
        [HttpGet]
        [Route("//loyalty/v1/points/")]
        [SwaggerOperation("RetrievePointsBalance")]
        [SwaggerResponse(200, type: typeof(RetrievePointsBalanceResponse))]
        public virtual IActionResult RetrievePointsBalance([FromQuery]long? playerId, [FromQuery]double? cardNo, [FromQuery]string membershipNo, [FromQuery]string testMembershipNo)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<RetrievePointsBalanceResponse>(exampleJson)
            : default(RetrievePointsBalanceResponse);
            return new ObjectResult(example);
        }
    }
}
