/*
 * Res.Grosvenor - Rank
 *
 * Rank Enterprise Services API is a collection of business services exposed over a RESTful inteface. This endpoint is specific to Grosvenor Casinos implementation.
 *
 * OpenAPI spec version: 1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Swashbuckle.SwaggerGen.Annotations;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    public class RetailAuthenticationV10ApiController : Controller
    { 

        /// <summary>
        /// Lookup
        /// </summary>
        /// <remarks>Returns BEDE player id from the persistance storage for the cardNo provided. If no record found, the response would be 404 (not found)</remarks>
        /// <param name="cardNo">card no issued to the retail customer</param>
        /// <response code="200"></response>
        /// <response code="404"></response>
        [HttpGet]
        [Route("//retailauthentication/v1/lookup")]
        [SwaggerOperation("Lookup")]
        [SwaggerResponse(200, type: typeof(LookupResponse))]
        public virtual IActionResult Lookup([FromQuery]double? cardNo)
        { 
            string exampleJson = null;
            
            var example = exampleJson != null
            ? JsonConvert.DeserializeObject<LookupResponse>(exampleJson)
            : default(LookupResponse);
            return new ObjectResult(example);
        }
    }
}
